---
sudo: required
dist: bionic

notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:

      #Installing istio-1.5.1?
      # istio: enabled knative: enabled linkerd: enabled
    # - name: "serverless knative linkerd service mesh  w microk8s snap on focal"
    #   dist: focal
    #   addons:
    #     snaps:
    #       - name: microk8s
    #         confinement: classic # or devmode
    #         channel: latest/stable # will be passed to --channel flag
    #   language: python
    #   # python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #     # - sudo make deploy-microk8s
    #     - sudo make deploy-linkerd-knative
    #   after_success:
    #     - deactivate

      #Installing istio-1.5.1?
      # istio: enabled knative: enabled linkerd: enabled
    - name: "serverless knative linkerd service mesh  w microk8s snap Python 3.7  on bionic"
      dist: bionic
      addons:
        snaps:
          - name: microk8s
            confinement: classic # or devmode
            channel: latest/stable # will be passed to --channel flag
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-linkerd-knative
      after_success:
        - deactivate

      #Installing istio-1.5.1?
      # istio: enabled knative: enabled linkerd: enabled
    # - name: "serverless knative linkerd service mesh  wo microk8s snap Python 3.7 on focal"
    #   dist: focal
    #   # addons:
    #   #   snaps:
    #   #     - name: microk8s
    #   #       confinement: classic # or devmode
    #   #       channel: latest/stable # will be passed to --channel flag
    #   language: python
    #   # python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #     - sudo make deploy-microk8s
    #     - sudo make deploy-linkerd-knative
    #   after_success:
    #     - deactivate

      #Installing istio-1.5.1?
      # istio: enabled knative: enabled linkerd: enabled
    # - name: "serverless knative linkerd service mesh  wo microk8s snap Python 3.7 on bionic"
    #   dist: bionic
    #   # addons:
    #   #   snaps:
    #   #     - name: microk8s
    #   #       confinement: classic # or devmode
    #   #       channel: latest/stable # will be passed to --channel flag
    #   language: python
    #   python: 3.7
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p $(which python3) ~venvpy3
    #     - source ~venvpy3/bin/activate
    #     - pip install -r requirements.txt
    #   script:
    #     - sudo make deploy-microk8s
    #     - sudo make deploy-linkerd-knative
    #   after_success:
    #     - deactivate
