---
sudo: required
dist: bionic

notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:

    - name: "linkerd service mesh  womicrok8s snap on focal"
      dist: focal
      addons:
        snaps:
          - name: microk8s
            confinement: classic
            channel: latest/stable
      language: python
      # python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-linkerd
      after_success:
        - deactivate


    - name: "linkerd service mesh  wo microk8s snap  on focal"
      dist: focal
      language: python
      # python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-linkerd
      after_success:
        - deactivate


    - name: "linkerd service mesh  womicrok8s snap Python 3.7 on bionic"
      dist: bionic
      addons:
        snaps:
          - name: microk8s
            confinement: classic
            channel: latest/stable
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-linkerd
      after_success:
        - deactivate


    - name: "linkerd service mesh  wo microk8s snap Python 3.7 on bionic"
      dist: bionic
      # addons:
      #   snaps:
      #     - name: microk8s
      #       confinement: classic
      #       channel: latest/stable
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-microk8s
        - sudo make deploy-linkerd
      after_success:
        - deactivate
