language: c
os:
  - linux
dist: # not both at the same time.
  # - focal
  - bionic
  # - xenial
arch:
  - amd64
  # - arm64
  # - ppc64le
  # - s390x
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - graphviz
  snaps:
    - name: microk8s
      confinement: classic # or devmode
      channel: latest/edge # will be passed to --channel flag

before_install:
  # - sudo snap install microk8s --classic --channel=latest/edge
  - sudo microk8s enable dashboard dns registry istio
script:
  - microk8s kubectl get all --all-namespaces
