language: c
os: # python virtual environments
  - linux
  - osx
  - windows
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - graphviz

fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt

before_install:
  - | # Python 3.7
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    # pip3 install virtualenv
    # virtualenv -p $(which python3) ~venvpy3
    # source ~venvpy3/bin/activate
    snap install microk8s --classic
    # microk8s kubectl get all --all-namespaces
    # microk8s enable dashboard dns registry istio
    # microk8s kubectl get all --all-namespaces
    fi
  - | #Python 3.7.5
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    # pip3 install virtualenv
    # virtualenv -p $(which python3) ~venvpy3
    # source ~venvpy3/bin/activate
    brew install ubuntu/microk8s/microk8s
    # microk8s install #Support for 'multipass' needs to be set up. Would you like to do that it now? [y/N]:
    # microk8s kubectl get all --all-namespaces
    # microk8s enable dashboard dns registry istio
    # microk8s kubectl get all --all-namespaces
    fi
  - | #Python 3.8
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
    PATH=/c/Python38:/c/Python38/Scripts:$PATH
    choco install python --version 3.8.1
    pip install virtualenv
    virtualenv $HOME/venv
    source $HOME/venv/Scripts/activate
    fi
<<: *fleet_install_tasks
<<: *fleet_script_tasks

script:
  - echo $(pwd)
