---
language: c
os:
  - osx
osx_image:
  - xcode12.2 #macOS 10.15.7
  - xcode12u #macOS 10.15.5
  - xcode12 #macOS 10.15.7
  - xcode11.5
  - xcode11.4
  - xcode11.3
  - xcode11.2
  - xcode11.1
  - xcode11
  - xcode10
  - xcode9.4
  # - xcode9
  # - xcode8 #ImportError: No module named zipp
addons:
 homebrew:
  casks:
  - mactex
  packages:
# nstaller: Error - Your CPU does not have the features necessary for Multipass. Installation cannot proceed.  
  # - multipass
# Warning: 'microk8s' formula is unreadable: No available formula with the name "microk8s"   
  # - microk8s

env:
  global:
  - VAGRANT_CURRENT_VERSION="$(curl -s https://checkpoint-api.hashicorp.com/v1/check/vagrant | jq -r -M '.current_version')"

notifications:
  slack:
    on_failure: always

fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt

before_install: #Python 2.7.17
  - pip install virtualenv
  - virtualenv -p $(which python2) ~venvpy2
  - source ~venvpy2/bin/activate
<<: *fleet_install_tasks
<<: *fleet_script_tasks

# https://microk8s.io/#tab-three__content
script:
  - brew install ubuntu/microk8s/microk8s
  # - microk8s install #Support for 'multipass' needs to be set up. Would you like to do that it now? [y/N]:
after_success:
  - deactivate
