---
language: c
os:
  - osx
osx_image:
  - xcode11.5
  - xcode11.4

addons:
 homebrew:
  casks:
  - mactex
  packages:
  - multipass

env:
  global:
  - VAGRANT_CURRENT_VERSION="$(curl -s https://checkpoint-api.hashicorp.com/v1/check/vagrant | jq -r -M '.current_version')"

notifications:
  slack:
    on_failure: always

fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt

before_install: #Python 2.7.17
  - pip install virtualenv
  - virtualenv -p $(which python2) ~venvpy2
  - source ~venvpy2/bin/activate
<<: *fleet_install_tasks
<<: *fleet_script_tasks

script:
  - brew list --versions

after_success:
  - deactivate
