language: c
os:
  - linux
dist: # only one distro is allowed
  # - focal
  - bionic
  # - xenial
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - graphviz
  snaps:
    - name: microk8s
      confinement: classic # or devmode
      channel: latest/edge # will be passed to --channel flag

before_install:
  # - sudo snap install microk8s --classic --channel=latest/edge
  # from server for: "/var/snap/microk8s/1763/actions/istio/istio-demo.yaml": Get "https://127.0.0.1:16443/apis/networking.istio.io/v1alpha3/namespaces/istio-system/destinationrules/istio-telemetry": dial tcp 127.0.0.1:16443: connect: connection refused
  # - sudo microk8s enable dashboard dns registry istio
  - sudo microk8s enable dashboard dns registry
script:
  - sudo microk8s kubectl get all --all-namespaces
