language: c
os:
  - linux
  - osx
dist: # not both at the same time.
  # - focal
  - bionic
  # - xenial
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - graphviz
  snaps:
       - microk8s

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then microk8s enable dashboard dns registry istio; fi

script:
  - echo $(pwd)
